Add serviceName to SS of octavia-ingress-controller (#755)
When applying current statefulSet sample, the error heppens like

$ kubectl apply -f octavia/deployment.yaml
error: error validating "octavia/deployment.yaml":
  error validating data: ValidationError(StatefulSet.spec):
  missing required field "serviceName" in io.k8s.api.apps.v1.State..

So this adds serviceName for avoiding the error.